-- L-Connector DDL
-- PostgreSQL 17

-- ============================================
-- ENUM型定義
-- ============================================

-- 管理者権限
CREATE TYPE admin_role_enum AS ENUM ('admin', 'normal');

-- LINE公式アカウント使用状況
CREATE TYPE usage_status_enum AS ENUM ('active', 'inactive');

-- 別LINE誘導
CREATE TYPE redirect_switch_enum AS ENUM ('on', 'off');

-- 振り分け先
CREATE TYPE distribution_target_enum AS ENUM ('target', 'no-target');

-- 配信状態チェック
CREATE TYPE ban_check_enum AS ENUM ('ok', 'ng', 'error');

-- 配信タイプ
CREATE TYPE delivery_type_enum AS ENUM ('push', 'reply', 'greet');

-- 配信状態
CREATE TYPE delivery_status_enum AS ENUM ('delivering', 'completed', 'error');

-- 挨拶メッセージ送信切り替え
CREATE TYPE send_switch_enum AS ENUM ('greet', 'unblock');

-- 送信ステータス
CREATE TYPE send_status_enum AS ENUM ('enabled', 'disabled');

-- 適用ステータス
CREATE TYPE application_status_enum AS ENUM ('enabled', 'disabled');

-- リッチメニューアクションタイプ
CREATE TYPE action_type_enum AS ENUM ('none', 'url');

-- ポストバック設定
CREATE TYPE postback_setting_enum AS ENUM ('none', 'meta', 'google', 'tiktok', 'line', 'custom');

-- ============================================
-- サイトテーブル
-- ============================================
CREATE TABLE sites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    cms_rest_api_key TEXT,
    cms_webhook_url TEXT,
    cms_webhook_key TEXT,
    rpa_api_key TEXT,
    conversion_api_url TEXT,
    using_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE sites IS 'サイト情報';
COMMENT ON COLUMN sites.name IS 'サイト名';
COMMENT ON COLUMN sites.cms_rest_api_key IS 'CMS向けREST APIキー';
COMMENT ON COLUMN sites.cms_webhook_url IS 'CMS向けWebhook URL';
COMMENT ON COLUMN sites.cms_webhook_key IS 'CMS向けWebhookキー';
COMMENT ON COLUMN sites.rpa_api_key IS 'RPA用APIキー';
COMMENT ON COLUMN sites.conversion_api_url IS 'コンバージョンAPIアクセス先URL';
COMMENT ON COLUMN sites.using_url IS 'サイトが使用するURL';

-- ============================================
-- 管理者テーブル
-- ============================================
CREATE TABLE admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    cognito_sub TEXT NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    name TEXT NOT NULL,
    login_id TEXT NOT NULL UNIQUE,
    role admin_role_enum NOT NULL,
    memo TEXT,
    last_login_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE admins IS '管理者';
COMMENT ON COLUMN admins.cognito_sub IS 'Cognito Sub';
COMMENT ON COLUMN admins.is_active IS '有効フラグ';
COMMENT ON COLUMN admins.role IS '権限 (admin/normal)';
COMMENT ON COLUMN admins.last_login_at IS '最終ログイン日時';

CREATE INDEX idx_admins_login_id ON admins(login_id);

-- ============================================
-- LINE公式アカウントテーブル
-- ============================================
CREATE TABLE line_official_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    usage_status usage_status_enum NOT NULL,
    basic_id TEXT,
    channel_id TEXT,
    channel_secret TEXT,
    access_token TEXT,
    access_token_expire TIMESTAMP WITH TIME ZONE,
    total_users INTEGER DEFAULT 0,
    total_non_blocked_users INTEGER DEFAULT 0,
    redirect_to_other_line redirect_switch_enum NOT NULL DEFAULT 'off',
    distribution_target distribution_target_enum,
    quota INTEGER,
    ban_check ban_check_enum,
    ban_check_at TIMESTAMP WITH TIME ZONE,
    memo TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE line_official_accounts IS 'LINE公式アカウント';
COMMENT ON COLUMN line_official_accounts.usage_status IS '使用状況 (active/inactive/disabled)';
COMMENT ON COLUMN line_official_accounts.basic_id IS 'LINE Basic ID';
COMMENT ON COLUMN line_official_accounts.total_users IS 'ユーザー合計数';
COMMENT ON COLUMN line_official_accounts.total_non_blocked_users IS '非ブロックユーザー合計数';
COMMENT ON COLUMN line_official_accounts.redirect_to_other_line IS '別LINE誘導 (on/off)';
COMMENT ON COLUMN line_official_accounts.distribution_target IS '振り分け先 (対象/除外)';
COMMENT ON COLUMN line_official_accounts.quota IS '配信数上限';
COMMENT ON COLUMN line_official_accounts.ban_check IS '配信状態 (ok/ng/error)';
COMMENT ON COLUMN line_official_accounts.ban_check_at IS 'BANチェック日時';

-- ============================================
-- LINE友達テーブル
-- ============================================
CREATE TABLE line_friends (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    advertisement_code_id BIGINT,
    messaging_api_user_id TEXT NOT NULL,
    messaging_api_user_id_cms TEXT NOT NULL,
    line_official_account_id BIGINT NOT NULL,
    is_blocked BOOLEAN NOT NULL DEFAULT false,
    query_string TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE line_friends IS 'LINE友達';
COMMENT ON COLUMN line_friends.advertisement_code_id IS '広告コードID';
COMMENT ON COLUMN line_friends.messaging_api_user_id IS 'Messaging API ユーザーID';
COMMENT ON COLUMN line_friends.messaging_api_user_id_cms IS 'CMS向けMessaging API ユーザーID';
COMMENT ON COLUMN line_friends.line_official_account_id IS 'LINE公式アカウントID';
COMMENT ON COLUMN line_friends.is_blocked IS 'ブロックされているかどうか';

CREATE INDEX idx_line_friends_messaging_api_user_id ON line_friends(messaging_api_user_id);
CREATE INDEX idx_line_friends_created_at ON line_friends(created_at);

-- ============================================
-- LINE友達履歴テーブル
-- ============================================
CREATE TABLE line_friend_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_friend_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE line_friend_histories IS 'LINE友達履歴（同一友達の複数回登録を記録）';
COMMENT ON COLUMN line_friend_histories.line_friend_id IS 'LINE友達ID';

CREATE INDEX idx_line_friend_histories_line_friend_id ON line_friend_histories(line_friend_id);

-- ============================================
-- LINE配信履歴テーブル
-- ============================================
CREATE TABLE line_delivery_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    delivery_type delivery_type_enum NOT NULL,
    delivery_status delivery_status_enum NOT NULL,
    accepted_count INTEGER,
    executed_count INTEGER NOT NULL DEFAULT 0,
    accepted_at TIMESTAMP WITH TIME ZONE,
    delivery_executed_at TIMESTAMP WITH TIME ZONE,
    execution_completed_at TIMESTAMP WITH TIME ZONE,
    json_data JSONB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE line_delivery_history IS 'LINE配信履歴';
COMMENT ON COLUMN line_delivery_history.delivery_type IS '配信タイプ (push/reply/greet)';
COMMENT ON COLUMN line_delivery_history.delivery_status IS '配信状態 (delivering/completed/error)';
COMMENT ON COLUMN line_delivery_history.accepted_count IS '受付件数';
COMMENT ON COLUMN line_delivery_history.executed_count IS '実行件数';
COMMENT ON COLUMN line_delivery_history.accepted_at IS '受付日時';
COMMENT ON COLUMN line_delivery_history.delivery_executed_at IS '配信実行日時';
COMMENT ON COLUMN line_delivery_history.execution_completed_at IS '実行完了日時';

CREATE INDEX idx_line_delivery_history_executed_at ON line_delivery_history(delivery_executed_at);

-- ============================================
-- CMS向けWebhook実行履歴テーブル
-- ============================================
CREATE TABLE cms_webhook_execution_history (
    webhook_event_id TEXT PRIMARY KEY,
    json_data JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE cms_webhook_execution_history IS 'CMS向けWebhook実行履歴';

-- ============================================
-- 挨拶メッセージテーブル
-- ============================================
CREATE TABLE greeting_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    send_switch send_switch_enum NOT NULL,
    settings json NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE greeting_messages IS '挨拶メッセージ';
COMMENT ON COLUMN greeting_messages.send_switch IS '送信切り替え (greet/unblock)';
COMMENT ON COLUMN greeting_messages.settings IS '設定';

-- ============================================
-- 自動応答メッセージテーブル
-- ============================================
CREATE TABLE auto_response_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    send_status send_status_enum NOT NULL,
    settings json NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE auto_response_messages IS '自動応答メッセージ';

-- ============================================
-- リッチメニューテーブル
-- ============================================
CREATE TABLE rich_menus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    application_status application_status_enum NOT NULL,
    template_type INTEGER NOT NULL CHECK (template_type IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)),
    settings JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE rich_menus IS 'リッチメニュー';
COMMENT ON COLUMN rich_menus.application_status IS '適用ステータス (enabled/disabled)';
COMMENT ON COLUMN rich_menus.template_type IS 'テンプレートタイプ (1-10)';

-- ============================================
-- 広告コードテーブル
-- ============================================
CREATE TABLE advertisement_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    advertisement_code TEXT NOT NULL,
    conversion_code TEXT,
    name TEXT NOT NULL,
    postback_setting postback_setting_enum NOT NULL,
    memo TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE advertisement_codes IS '広告コード';
COMMENT ON COLUMN advertisement_codes.advertisement_code IS '広告コード';
COMMENT ON COLUMN advertisement_codes.conversion_code IS 'コンバージョンコード';
COMMENT ON COLUMN advertisement_codes.postback_setting IS 'ポストバック設定 (none/meta/google/tiktok/line/custom)';

CREATE UNIQUE INDEX idx_advertisement_codes_code ON advertisement_codes(advertisement_code);

-- ============================================
-- 広告コードカスタム設定テーブル
-- ============================================
CREATE TABLE advertisement_code_custom_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    advertisement_code_id BIGINT NOT NULL,
    custom_settings JSON NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE advertisement_code_custom_settings IS '広告コードカスタム設定';
COMMENT ON COLUMN advertisement_code_custom_settings.advertisement_code_id IS '広告コードID';
COMMENT ON COLUMN advertisement_code_custom_settings.custom_settings IS 'カスタム設定 (JSON)';

-- ============================================
-- ポストバック履歴テーブル
-- ============================================
CREATE TABLE postback_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    advertisement_code_id BIGINT NOT NULL,
    line_friend_id BIGINT,
    execution_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE postback_history IS 'ポストバック履歴';
COMMENT ON COLUMN postback_history.advertisement_code_id IS '広告コードID';
COMMENT ON COLUMN postback_history.line_friend_id IS 'LINE友達ID';
COMMENT ON COLUMN postback_history.execution_url IS '実行URL';

CREATE INDEX idx_postback_history_created_at ON postback_history(created_at);

-- ============================================
-- マテリアライズドビュー: 年月単位集計
-- ============================================
CREATE MATERIALIZED VIEW stats_monthly AS
SELECT
    DATE_TRUNC('month', created_at) AS month,
    COUNT(*) AS friend_registrations,
    0 AS push_deliveries,
    0 AS reply_deliveries
FROM line_friends
GROUP BY DATE_TRUNC('month', created_at)

UNION ALL

SELECT
    DATE_TRUNC('month', delivery_executed_at) AS month,
    0 AS friend_registrations,
    SUM(CASE WHEN delivery_type = 'push' THEN executed_count ELSE 0 END) AS push_deliveries,
    SUM(CASE WHEN delivery_type = 'reply' THEN executed_count ELSE 0 END) AS reply_deliveries
FROM line_delivery_history
WHERE delivery_executed_at IS NOT NULL
GROUP BY DATE_TRUNC('month', delivery_executed_at);

COMMENT ON MATERIALIZED VIEW stats_monthly IS '年月単位の集計（友達登録、push配信、reply配信）';

CREATE INDEX idx_stats_monthly_month ON stats_monthly(month);

-- ============================================
-- マテリアライズドビュー: 日単位集計
-- ============================================
CREATE MATERIALIZED VIEW stats_daily AS
SELECT
    DATE_TRUNC('day', created_at) AS day,
    DATE_TRUNC('month', created_at) AS month,
    COUNT(*) AS friend_registrations,
    0 AS push_deliveries,
    0 AS reply_deliveries
FROM line_friends
GROUP BY DATE_TRUNC('day', created_at), DATE_TRUNC('month', created_at)

UNION ALL

SELECT
    DATE_TRUNC('day', delivery_executed_at) AS day,
    DATE_TRUNC('month', delivery_executed_at) AS month,
    0 AS friend_registrations,
    SUM(CASE WHEN delivery_type = 'push' THEN executed_count ELSE 0 END) AS push_deliveries,
    SUM(CASE WHEN delivery_type = 'reply' THEN executed_count ELSE 0 END) AS reply_deliveries
FROM line_delivery_history
WHERE delivery_executed_at IS NOT NULL
GROUP BY DATE_TRUNC('day', delivery_executed_at), DATE_TRUNC('month', delivery_executed_at);

COMMENT ON MATERIALIZED VIEW stats_daily IS '日単位の集計（友達登録、push配信、reply配信）年月で検索可能';

CREATE INDEX idx_stats_daily_day ON stats_daily(day);
CREATE INDEX idx_stats_daily_month ON stats_daily(month);

-- ============================================
-- マテリアライズドビュー: 時間単位集計
-- ============================================
CREATE MATERIALIZED VIEW stats_hourly AS
SELECT
    DATE_TRUNC('hour', created_at) AS hour,
    DATE_TRUNC('month', created_at) AS month,
    COUNT(*) AS friend_registrations,
    0 AS push_deliveries,
    0 AS reply_deliveries
FROM line_friends
GROUP BY DATE_TRUNC('hour', created_at), DATE_TRUNC('month', created_at)

UNION ALL

SELECT
    DATE_TRUNC('hour', delivery_executed_at) AS hour,
    DATE_TRUNC('month', delivery_executed_at) AS month,
    0 AS friend_registrations,
    SUM(CASE WHEN delivery_type = 'push' THEN executed_count ELSE 0 END) AS push_deliveries,
    SUM(CASE WHEN delivery_type = 'reply' THEN executed_count ELSE 0 END) AS reply_deliveries
FROM line_delivery_history
WHERE delivery_executed_at IS NOT NULL
GROUP BY DATE_TRUNC('hour', delivery_executed_at), DATE_TRUNC('month', delivery_executed_at);

COMMENT ON MATERIALIZED VIEW stats_hourly IS '時間単位の集計（友達登録、push配信、reply配信）年月で検索可能';

CREATE INDEX idx_stats_hourly_hour ON stats_hourly(hour);
CREATE INDEX idx_stats_hourly_month ON stats_hourly(month);

-- ============================================
-- マテリアライズドビュー更新用関数
-- ============================================
COMMENT ON MATERIALIZED VIEW stats_monthly IS 'マテリアライズドビュー更新: REFRESH MATERIALIZED VIEW CONCURRENTLY stats_monthly;';
COMMENT ON MATERIALIZED VIEW stats_daily IS 'マテリアライズドビュー更新: REFRESH MATERIALIZED VIEW CONCURRENTLY stats_daily;';
COMMENT ON MATERIALIZED VIEW stats_hourly IS 'マテリアライズドビュー更新: REFRESH MATERIALIZED VIEW CONCURRENTLY stats_hourly;';